---
- name: Deploy elrond container
  hosts: gce_instances_ips
  become: yes
  become_method: sudo
  roles:
    - role: elrond
      vars:
        shard_count: 4
        shard_volume_prefix: "/srv/elrond"

